/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import signingToday.client.model.SignerRecord;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuditRecord
 */
public class AuditRecordTest {
    private final AuditRecord model = new AuditRecord();

    /**
     * Model tests for AuditRecord
     */
    @Test
    public void testAuditRecord() {
        // TODO: test AuditRecord
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'at'
     */
    @Test
    public void atTest() {
        // TODO: test at
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'signer'
     */
    @Test
    public void signerTest() {
        // TODO: test signer
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'dstId'
     */
    @Test
    public void dstIdTest() {
        // TODO: test dstId
    }

    /**
     * Test the property 'documentId'
     */
    @Test
    public void documentIdTest() {
        // TODO: test documentId
    }

    /**
     * Test the property 'fillableFormId'
     */
    @Test
    public void fillableFormIdTest() {
        // TODO: test fillableFormId
    }

    /**
     * Test the property 'signatureRequestId'
     */
    @Test
    public void signatureRequestIdTest() {
        // TODO: test signatureRequestId
    }

    /**
     * Test the property 'noteId'
     */
    @Test
    public void noteIdTest() {
        // TODO: test noteId
    }

}
