/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import signingToday.client.model.Document;
import signingToday.client.model.LFResource;
import signingToday.client.model.Signature;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DigitalSignatureTransaction
 */
public class DigitalSignatureTransactionTest {
    private final DigitalSignatureTransaction model = new DigitalSignatureTransaction();

    /**
     * Model tests for DigitalSignatureTransaction
     */
    @Test
    public void testDigitalSignatureTransaction() {
        // TODO: test DigitalSignatureTransaction
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'replaces'
     */
    @Test
    public void replacesTest() {
        // TODO: test replaces
    }

    /**
     * Test the property 'replacedBy'
     */
    @Test
    public void replacedByTest() {
        // TODO: test replacedBy
    }

    /**
     * Test the property 'createdByUser'
     */
    @Test
    public void createdByUserTest() {
        // TODO: test createdByUser
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    public void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'resources'
     */
    @Test
    public void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'signatures'
     */
    @Test
    public void signaturesTest() {
        // TODO: test signatures
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'publicTemplate'
     */
    @Test
    public void publicTemplateTest() {
        // TODO: test publicTemplate
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

    /**
     * Test the property 'visibleTo'
     */
    @Test
    public void visibleToTest() {
        // TODO: test visibleTo
    }

    /**
     * Test the property 'ccGroups'
     */
    @Test
    public void ccGroupsTest() {
        // TODO: test ccGroups
    }

    /**
     * Test the property 'ccUsers'
     */
    @Test
    public void ccUsersTest() {
        // TODO: test ccUsers
    }

    /**
     * Test the property 'urgent'
     */
    @Test
    public void urgentTest() {
        // TODO: test urgent
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
