/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import signingToday.client.model.FillableForm;
import signingToday.client.model.SignatureRequest;
import signingToday.client.model.SignersGroup;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Document
 */
public class DocumentTest {
    private final Document model = new Document();

    /**
     * Model tests for Document
     */
    @Test
    public void testDocument() {
        // TODO: test Document
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'plainDocumentUuid'
     */
    @Test
    public void plainDocumentUuidTest() {
        // TODO: test plainDocumentUuid
    }

    /**
     * Test the property 'filledDocumentUuid'
     */
    @Test
    public void filledDocumentUuidTest() {
        // TODO: test filledDocumentUuid
    }

    /**
     * Test the property 'signedDocumentUuid'
     */
    @Test
    public void signedDocumentUuidTest() {
        // TODO: test signedDocumentUuid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'forms'
     */
    @Test
    public void formsTest() {
        // TODO: test forms
    }

    /**
     * Test the property 'signatureRequests'
     */
    @Test
    public void signatureRequestsTest() {
        // TODO: test signatureRequests
    }

    /**
     * Test the property 'signerGroups'
     */
    @Test
    public void signerGroupsTest() {
        // TODO: test signerGroups
    }

}
