/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FillableForm
 */
public class FillableFormTest {
    private final FillableForm model = new FillableForm();

    /**
     * Model tests for FillableForm
     */
    @Test
    public void testFillableForm() {
        // TODO: test FillableForm
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'documentId'
     */
    @Test
    public void documentIdTest() {
        // TODO: test documentId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'positionX'
     */
    @Test
    public void positionXTest() {
        // TODO: test positionX
    }

    /**
     * Test the property 'positionY'
     */
    @Test
    public void positionYTest() {
        // TODO: test positionY
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'signerId'
     */
    @Test
    public void signerIdTest() {
        // TODO: test signerId
    }

    /**
     * Test the property 'toFill'
     */
    @Test
    public void toFillTest() {
        // TODO: test toFill
    }

    /**
     * Test the property 'filled'
     */
    @Test
    public void filledTest() {
        // TODO: test filled
    }

    /**
     * Test the property 'invisible'
     */
    @Test
    public void invisibleTest() {
        // TODO: test invisible
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
