/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * IdentityProviderDataTokenInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-24T08:13:36.809Z[GMT]")
public class IdentityProviderDataTokenInfo {
  public static final String SERIALIZED_NAME_UL_MIN_PIN_LEN = "ulMinPinLen";
  @SerializedName(SERIALIZED_NAME_UL_MIN_PIN_LEN)
  private BigDecimal ulMinPinLen;

  public static final String SERIALIZED_NAME_MANUFACTURER_I_D = "manufacturerID";
  @SerializedName(SERIALIZED_NAME_MANUFACTURER_I_D)
  private String manufacturerID;

  public static final String SERIALIZED_NAME_UL_FREE_PUBLIC_MEMORY = "ulFreePublicMemory";
  @SerializedName(SERIALIZED_NAME_UL_FREE_PUBLIC_MEMORY)
  private BigDecimal ulFreePublicMemory;

  public static final String SERIALIZED_NAME_SERIAL_NUMBER = "serialNumber";
  @SerializedName(SERIALIZED_NAME_SERIAL_NUMBER)
  private String serialNumber;

  public static final String SERIALIZED_NAME_UL_TOTAL_PUBLIC_MEMORY = "ulTotalPublicMemory";
  @SerializedName(SERIALIZED_NAME_UL_TOTAL_PUBLIC_MEMORY)
  private BigDecimal ulTotalPublicMemory;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  private BigDecimal flags;

  public static final String SERIALIZED_NAME_UL_TOTAL_PRIVATE_MEMORY = "ulTotalPrivateMemory";
  @SerializedName(SERIALIZED_NAME_UL_TOTAL_PRIVATE_MEMORY)
  private BigDecimal ulTotalPrivateMemory;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private String model;

  public static final String SERIALIZED_NAME_UL_FREE_PRIVATE_MEMORY = "ulFreePrivateMemory";
  @SerializedName(SERIALIZED_NAME_UL_FREE_PRIVATE_MEMORY)
  private BigDecimal ulFreePrivateMemory;

  public static final String SERIALIZED_NAME_UL_MAX_PIN_LEN = "ulMaxPinLen";
  @SerializedName(SERIALIZED_NAME_UL_MAX_PIN_LEN)
  private BigDecimal ulMaxPinLen;


  public IdentityProviderDataTokenInfo ulMinPinLen(BigDecimal ulMinPinLen) {
    
    this.ulMinPinLen = ulMinPinLen;
    return this;
  }

   /**
   * Get ulMinPinLen
   * @return ulMinPinLen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "")

  public BigDecimal getUlMinPinLen() {
    return ulMinPinLen;
  }


  public void setUlMinPinLen(BigDecimal ulMinPinLen) {
    this.ulMinPinLen = ulMinPinLen;
  }


  public IdentityProviderDataTokenInfo manufacturerID(String manufacturerID) {
    
    this.manufacturerID = manufacturerID;
    return this;
  }

   /**
   * Get manufacturerID
   * @return manufacturerID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Bit4id", value = "")

  public String getManufacturerID() {
    return manufacturerID;
  }


  public void setManufacturerID(String manufacturerID) {
    this.manufacturerID = manufacturerID;
  }


  public IdentityProviderDataTokenInfo ulFreePublicMemory(BigDecimal ulFreePublicMemory) {
    
    this.ulFreePublicMemory = ulFreePublicMemory;
    return this;
  }

   /**
   * Get ulFreePublicMemory
   * @return ulFreePublicMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "41168", value = "")

  public BigDecimal getUlFreePublicMemory() {
    return ulFreePublicMemory;
  }


  public void setUlFreePublicMemory(BigDecimal ulFreePublicMemory) {
    this.ulFreePublicMemory = ulFreePublicMemory;
  }


  public IdentityProviderDataTokenInfo serialNumber(String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7430010005961358", value = "")

  public String getSerialNumber() {
    return serialNumber;
  }


  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  public IdentityProviderDataTokenInfo ulTotalPublicMemory(BigDecimal ulTotalPublicMemory) {
    
    this.ulTotalPublicMemory = ulTotalPublicMemory;
    return this;
  }

   /**
   * Get ulTotalPublicMemory
   * @return ulTotalPublicMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "80000", value = "")

  public BigDecimal getUlTotalPublicMemory() {
    return ulTotalPublicMemory;
  }


  public void setUlTotalPublicMemory(BigDecimal ulTotalPublicMemory) {
    this.ulTotalPublicMemory = ulTotalPublicMemory;
  }


  public IdentityProviderDataTokenInfo label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CNS", value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public IdentityProviderDataTokenInfo flags(BigDecimal flags) {
    
    this.flags = flags;
    return this;
  }

   /**
   * Get flags
   * @return flags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1037", value = "")

  public BigDecimal getFlags() {
    return flags;
  }


  public void setFlags(BigDecimal flags) {
    this.flags = flags;
  }


  public IdentityProviderDataTokenInfo ulTotalPrivateMemory(BigDecimal ulTotalPrivateMemory) {
    
    this.ulTotalPrivateMemory = ulTotalPrivateMemory;
    return this;
  }

   /**
   * Get ulTotalPrivateMemory
   * @return ulTotalPrivateMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "80000", value = "")

  public BigDecimal getUlTotalPrivateMemory() {
    return ulTotalPrivateMemory;
  }


  public void setUlTotalPrivateMemory(BigDecimal ulTotalPrivateMemory) {
    this.ulTotalPrivateMemory = ulTotalPrivateMemory;
  }


  public IdentityProviderDataTokenInfo model(String model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "JS2048 (LB)", value = "")

  public String getModel() {
    return model;
  }


  public void setModel(String model) {
    this.model = model;
  }


  public IdentityProviderDataTokenInfo ulFreePrivateMemory(BigDecimal ulFreePrivateMemory) {
    
    this.ulFreePrivateMemory = ulFreePrivateMemory;
    return this;
  }

   /**
   * Get ulFreePrivateMemory
   * @return ulFreePrivateMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "41168", value = "")

  public BigDecimal getUlFreePrivateMemory() {
    return ulFreePrivateMemory;
  }


  public void setUlFreePrivateMemory(BigDecimal ulFreePrivateMemory) {
    this.ulFreePrivateMemory = ulFreePrivateMemory;
  }


  public IdentityProviderDataTokenInfo ulMaxPinLen(BigDecimal ulMaxPinLen) {
    
    this.ulMaxPinLen = ulMaxPinLen;
    return this;
  }

   /**
   * Get ulMaxPinLen
   * @return ulMaxPinLen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "8", value = "")

  public BigDecimal getUlMaxPinLen() {
    return ulMaxPinLen;
  }


  public void setUlMaxPinLen(BigDecimal ulMaxPinLen) {
    this.ulMaxPinLen = ulMaxPinLen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityProviderDataTokenInfo identityProviderDataTokenInfo = (IdentityProviderDataTokenInfo) o;
    return Objects.equals(this.ulMinPinLen, identityProviderDataTokenInfo.ulMinPinLen) &&
        Objects.equals(this.manufacturerID, identityProviderDataTokenInfo.manufacturerID) &&
        Objects.equals(this.ulFreePublicMemory, identityProviderDataTokenInfo.ulFreePublicMemory) &&
        Objects.equals(this.serialNumber, identityProviderDataTokenInfo.serialNumber) &&
        Objects.equals(this.ulTotalPublicMemory, identityProviderDataTokenInfo.ulTotalPublicMemory) &&
        Objects.equals(this.label, identityProviderDataTokenInfo.label) &&
        Objects.equals(this.flags, identityProviderDataTokenInfo.flags) &&
        Objects.equals(this.ulTotalPrivateMemory, identityProviderDataTokenInfo.ulTotalPrivateMemory) &&
        Objects.equals(this.model, identityProviderDataTokenInfo.model) &&
        Objects.equals(this.ulFreePrivateMemory, identityProviderDataTokenInfo.ulFreePrivateMemory) &&
        Objects.equals(this.ulMaxPinLen, identityProviderDataTokenInfo.ulMaxPinLen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ulMinPinLen, manufacturerID, ulFreePublicMemory, serialNumber, ulTotalPublicMemory, label, flags, ulTotalPrivateMemory, model, ulFreePrivateMemory, ulMaxPinLen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityProviderDataTokenInfo {\n");
    sb.append("    ulMinPinLen: ").append(toIndentedString(ulMinPinLen)).append("\n");
    sb.append("    manufacturerID: ").append(toIndentedString(manufacturerID)).append("\n");
    sb.append("    ulFreePublicMemory: ").append(toIndentedString(ulFreePublicMemory)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    ulTotalPublicMemory: ").append(toIndentedString(ulTotalPublicMemory)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    ulTotalPrivateMemory: ").append(toIndentedString(ulTotalPrivateMemory)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    ulFreePrivateMemory: ").append(toIndentedString(ulFreePrivateMemory)).append("\n");
    sb.append("    ulMaxPinLen: ").append(toIndentedString(ulMaxPinLen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

