/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import signingToday.client.model.OrganizationPrivateSettings;
import signingToday.client.model.OrganizationPublicSettings;
import signingToday.client.model.OrganizationSettings;

/**
 * Organization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-24T08:13:36.809Z[GMT]")
public class Organization {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EMAIL_OVERRIDE_FOLDER_PATH = "emailOverrideFolderPath";
  @SerializedName(SERIALIZED_NAME_EMAIL_OVERRIDE_FOLDER_PATH)
  private String emailOverrideFolderPath;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CONTACT_EMAIL = "contactEmail";
  @SerializedName(SERIALIZED_NAME_CONTACT_EMAIL)
  private String contactEmail;

  public static final String SERIALIZED_NAME_CONTACT_PHONE = "contactPhone";
  @SerializedName(SERIALIZED_NAME_CONTACT_PHONE)
  private String contactPhone;

  public static final String SERIALIZED_NAME_NATION = "nation";
  @SerializedName(SERIALIZED_NAME_NATION)
  private String nation;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_DELETED_AT = "deletedAt";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  private OffsetDateTime deletedAt;

  public static final String SERIALIZED_NAME_PRIVATE_SETTINGS = "privateSettings";
  @SerializedName(SERIALIZED_NAME_PRIVATE_SETTINGS)
  private OrganizationPrivateSettings privateSettings;

  public static final String SERIALIZED_NAME_PUBLIC_SETTINGS = "publicSettings";
  @SerializedName(SERIALIZED_NAME_PUBLIC_SETTINGS)
  private OrganizationPublicSettings publicSettings;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  private OrganizationSettings settings;


  public Organization id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Organization emailOverrideFolderPath(String emailOverrideFolderPath) {
    
    this.emailOverrideFolderPath = emailOverrideFolderPath;
    return this;
  }

   /**
   * Get emailOverrideFolderPath
   * @return emailOverrideFolderPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmailOverrideFolderPath() {
    return emailOverrideFolderPath;
  }


  public void setEmailOverrideFolderPath(String emailOverrideFolderPath) {
    this.emailOverrideFolderPath = emailOverrideFolderPath;
  }


  public Organization name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Organization contactEmail(String contactEmail) {
    
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContactEmail() {
    return contactEmail;
  }


  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }


  public Organization contactPhone(String contactPhone) {
    
    this.contactPhone = contactPhone;
    return this;
  }

   /**
   * Get contactPhone
   * @return contactPhone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContactPhone() {
    return contactPhone;
  }


  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }


  public Organization nation(String nation) {
    
    this.nation = nation;
    return this;
  }

   /**
   * Get nation
   * @return nation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNation() {
    return nation;
  }


  public void setNation(String nation) {
    this.nation = nation;
  }


  public Organization city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2007-04-02T19:30:10Z", value = "")

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }




  public Organization privateSettings(OrganizationPrivateSettings privateSettings) {
    
    this.privateSettings = privateSettings;
    return this;
  }

   /**
   * Get privateSettings
   * @return privateSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrganizationPrivateSettings getPrivateSettings() {
    return privateSettings;
  }


  public void setPrivateSettings(OrganizationPrivateSettings privateSettings) {
    this.privateSettings = privateSettings;
  }


  public Organization publicSettings(OrganizationPublicSettings publicSettings) {
    
    this.publicSettings = publicSettings;
    return this;
  }

   /**
   * Get publicSettings
   * @return publicSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrganizationPublicSettings getPublicSettings() {
    return publicSettings;
  }


  public void setPublicSettings(OrganizationPublicSettings publicSettings) {
    this.publicSettings = publicSettings;
  }


  public Organization settings(OrganizationSettings settings) {
    
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrganizationSettings getSettings() {
    return settings;
  }


  public void setSettings(OrganizationSettings settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.id, organization.id) &&
        Objects.equals(this.emailOverrideFolderPath, organization.emailOverrideFolderPath) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.contactEmail, organization.contactEmail) &&
        Objects.equals(this.contactPhone, organization.contactPhone) &&
        Objects.equals(this.nation, organization.nation) &&
        Objects.equals(this.city, organization.city) &&
        Objects.equals(this.deletedAt, organization.deletedAt) &&
        Objects.equals(this.privateSettings, organization.privateSettings) &&
        Objects.equals(this.publicSettings, organization.publicSettings) &&
        Objects.equals(this.settings, organization.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, emailOverrideFolderPath, name, contactEmail, contactPhone, nation, city, deletedAt, privateSettings, publicSettings, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    emailOverrideFolderPath: ").append(toIndentedString(emailOverrideFolderPath)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    nation: ").append(toIndentedString(nation)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    privateSettings: ").append(toIndentedString(privateSettings)).append("\n");
    sb.append("    publicSettings: ").append(toIndentedString(publicSettings)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

