/*
 * Signing Today Web
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package signingToday.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * The Mapping of the Roles will be used in the new DST
 */
@ApiModel(description = "The Mapping of the Roles will be used in the new DST")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-24T08:13:36.809Z[GMT]")
public class SignerInstance {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SURNAME = "surname";
  @SerializedName(SERIALIZED_NAME_SURNAME)
  private String surname;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_USER_U_U_I_D = "userUUID";
  @SerializedName(SERIALIZED_NAME_USER_U_U_I_D)
  private UUID userUUID;


  public SignerInstance name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the Signer
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Adam", value = "Name of the Signer")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SignerInstance surname(String surname) {
    
    this.surname = surname;
    return this;
  }

   /**
   * Surname of the Signer
   * @return surname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Smith", value = "Surname of the Signer")

  public String getSurname() {
    return surname;
  }


  public void setSurname(String surname) {
    this.surname = surname;
  }


  public SignerInstance email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Email address of the Signer
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "adam.smith@email.com", value = "Email address of the Signer")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public SignerInstance phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Phone number of the Signer
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+013392213450", value = "Phone number of the Signer")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public SignerInstance userUUID(UUID userUUID) {
    
    this.userUUID = userUUID;
    return this;
  }

   /**
   * LibroFirma UserUUID, if associated to. Otherwise null.
   * @return userUUID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "a845e772-cb45-466f-9c02-d9dd06afa36e", value = "LibroFirma UserUUID, if associated to. Otherwise null.")

  public UUID getUserUUID() {
    return userUUID;
  }


  public void setUserUUID(UUID userUUID) {
    this.userUUID = userUUID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignerInstance signerInstance = (SignerInstance) o;
    return Objects.equals(this.name, signerInstance.name) &&
        Objects.equals(this.surname, signerInstance.surname) &&
        Objects.equals(this.email, signerInstance.email) &&
        Objects.equals(this.phone, signerInstance.phone) &&
        Objects.equals(this.userUUID, signerInstance.userUUID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname, email, phone, userUUID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignerInstance {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    userUUID: ").append(toIndentedString(userUUID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

